### ISSUE TITLE
Implicit undeclared dependency on Dist::Zilla::Tester

### ISSUE THREAD

**Issue by kentfredric** [dagolden/Dist-Zilla-Plugin-Meta-Contributors#2]
Similar problem to https://github.com/dagolden/Dist-Zilla-Plugin-CheckExtraTests/issues/22 , but is in fact failing with Test::DZil changed.

http://www.cpantesters.org/cpan/report/cdcca31e-e0c8-11e4-9e72-12be66b533a2 

https://github.com/dagolden/Dist-Zilla-Plugin-Meta-Contributors/blob/master/t/contributors.t#L6-L18

**Comment by karenetheridge** [comment]
This is closable now - fixed in 0.003.
